### ISSUE TITLE
New 20.1.1 release on pypi?

### ISSUE THREAD

**Issue by sbp-jvb** [mahmoud/face#17]
Hi,

I noticed a new Python 3 wheel build is uploaded to [pypi](https://pypi.org/project/face/20.1.1/) for version 20.1.1. The Wheel is uploaded on pypi on Jan 19, 2023 with SHA256 hash: ca3a1d8b8b6aa8e61d62a300e9ee24e09c062aceda549e9a640128e4fa0f4559, yet there is no new release/tag on this project to match this. The hashes for the source distribution and Python 2 wheel release for 20.1.1 have not changed.
Could you please indicate if you uploaded this distribution and why?

**Comment by mahmoud** [comment]
Yep, thanks for checking, here's the background: https://github.com/mahmoud/face/issues/16#issuecomment-1397070933

**Comment by sbp-jvb** [comment]
Thank you for the quick response!
I'm sorry I should've checked the closed issues.
