### ISSUE TITLE
Add link to API docs from README

### ISSUE THREAD

**Issue by moshez** [mahmoud/face#9]
It is not obvious where the canonical documentation lives

**Comment by mahmoud** [comment]
That's a great point! Will set up an RTD ASAP.

**Comment by astronouth7303** [comment]
Yup, was just about to file this bug, nothing links to anything so discoverability is really really low.

**Comment by mahmoud** [comment]
Fixed just now. I added a couple larger use case links, too. Thanks for the reminder!
